version: "3.2"
services:
  redis:
    image: redis:alpine
    command: redis-server
    sysctls:
      - net.core.somaxconn=1024
    ports:
      - "6379:6379"

  golang_url_shortener:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
    environment:
      - GUS_BASE_URL=https://s.b0n.pl
      - GUS_BACKEND=redis
      - GUS_REDIS_HOST=redis:6379
    links:
      - redis
    depends_on:
      - redis
    restart: always
